### PR TITLE
Fixed and documented .gitignore

### LINKED ISSUE #7: .gitignore contains bad files?
I think that these 2 files shouldn't be in gitignore.
- public/font/demo.html
- public/font/stylesheet.css

### PR DESCRIPTION
**Pull request by SamuPert**
I edited the .gitignore file by removing unnecessary files.

Closes #7

### CODE REVIEW

**Comment by emi-2205** [comment]
I added public/font/demo.html and public/font/stylesheet.css cause they are font example in the font folder

**Review by Paolo-Beci — APPROVED** [review]
love gitignores

**Comment by SamuPert** [comment]
> I added public/font/demo.html and public/font/stylesheet.css cause they are font example in the font folder

Oh I see.
Can you elaborate a bit more?

Do you still need them to be in the .gitignore?
Otherwise you can delete them from your local folder and we can merge this pull request.

**Review by emi-2205 — APPROVED** [review]
yes you are right
We already have all necessary fonts in the font folder and, hence those 2 examples are no longer helpful, we can delete both them

**Pull request merged**
