### PR TITLE
migration-to-bootstrap merge

### PR DESCRIPTION
**Pull request by emi-2205**
# Migration to Bootstrap

## launched commands
- npm i --save bootstrap @popperjs/core
- npm i --save-dev autoprefixer css-loader postcss-loader sass sass-loader style-loader
## updated files
- postcss.config.js
- popup.scss

### CODE REVIEW

**Review by Paolo-Beci — COMMENTED** [review]
me piace

**Review by SamuPert — COMMENTED** [review]
Looks good to me!
Awesome!

**Review by SamuPert — APPROVED** [review]
Looks good to me!
Awesome!

**Review by Paolo-Beci — APPROVED** [review]
me piace++

**Pull request merged**
